defaultEntryPoints = ["http", "https"]

[accessLog]
filePath = "/logs/access.log"

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
exposedbydefault = false
logLevel = "DEBUG"  # TODO
network = "webgateway"
watch = true


[entryPoints]

  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"

  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]


[acme]
storage = "acme.json"
entryPoint = "https"
onHostRule = true

  [acme.httpChallenge]
  entryPoint = "http"
