version: "3.7"

services:

  platform:
    build:
      context: .
      dockerfile: Dockerfile-platform
      args:
        RESEARCHSPACE_TAG: ${RESEARCHSPACE_TAG}
    restart: always
    stop_grace_period: "1m"
    depends_on:
      - blazegraph
    networks:
      - default
      - webgateway
    volumes:
      - researchspace-data:/runtime-data
    environment:
      JAVA_OPTS: ""
      # some notes regarding the -DappsDirectory setting:
      # - it relies on the invokation of jetty from the entrypoint.sh with
      #   expanded environment variables in the order
      #   $RUNTIME_OPTS $PLATFORM_OPTS
      # - and the fact that the JVM favors the rightmost definition of an
      #   option within these environment variables
      # - it is a workaround for an issue that might be solved with
      #   ResearchSpace 3.2
      PLATFORM_OPTS: >
        -DappsDirectory=/wrapps
        -Dconfig.environment.sparqlEndpoint=http://blazegraph:8080/blazegraph/sparql
        -Dlog4j.configurationFile=file:///var/lib/jetty/webapps/etc/log4j2.xml
        ${EXTRA_PLATFORM_PROPERTIES}
    labels:
      - traefik.frontend.rule=Host:${WEB_DOMAIN}
      - traefik.port=8080
      - traefik.enable=true

  blazegraph:
    image: researchspace/blazegraph:${BLAZEGRAPH_TAG}
    restart: always
    stop_grace_period: "1m"
    environment:
      JAVA_OPTS: ""
    volumes:
      - blazegraph-data:/blazegraph-data

  backup:
    image: borgbackup
    restart: always
    userns_mode: host
    network_mode: none
    labels:
      deck-chores.backup.command: "/bin/sh /backup.sh"
      deck-chores.backup.cron: "1 0 0"
      deck-chores.backup.jitter: "30m"
    environment:
      WEB_DOMAIN: ${WEB_DOMAIN}
      BORG_PASSPHRASE: ${BORG_PASSPHRASE}
      BORG_REPO: /borg_repository
    volumes:
      - ./backup.sh:/backup.sh:ro
      - ${BORG_REPOSITORY}:/borg_repository
      - blazegraph-data:/src/blazegraph-data:ro
      - researchspace-data:/src/researchspace-data:ro
      - /var/lib/borg:/var/lib/borg


volumes:
  blazegraph-data:
  researchspace-data:


networks:
  webgateway:
    external:
      name: webgateway
