version: "3.7"

services:
  webserver:
    build: ./image
    restart: always
    networks:
      - webgateway
    volumes:
      - ${ASSETS_ROOT_DIR}:/usr/share/nginx/html:ro
    labels:
      - traefik.frontend.rule=Host:${WEB_DOMAIN}
      - traefik.port=80
      - traefik.enable=true

networks:
  webgateway:
    external:
      name: webgateway
