---

- name: set minimum password length to twelve
  replace:
    path: /etc/pam.d/common-password
    regexp: ^(password.*pam_unix[.]so) (?!obscure sha512 minlen=12).*$
    replace: \1 obscure sha512 minlen=12

- include_tasks: _add_user.yml
  vars:
    user: "{{ item.name }}"
    pub_key: "{{ item.pub_key }}"
  with_items: "{{ users }}"
