---

- listen: reload journald
  command: systemctl reload systemd-journald.service

- listen: reload sshd
  command: systemctl reload sshd.service

- listen: reload systemd
  command: systemctl daemon-reload

- listen: restart dockerd
  command: systemctl restart docker.service
