---

- name: add repo signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: "0x8D81803C0EBFCD88"

- name: add package repository
  apt_repository:
    filename: docker
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"

- name: create Docker configuration folder
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: ug=rwx,o=

- name: write Docker configuration
  copy:
    dest: /etc/docker/daemon.json
    content: '{"log-driver": "journald", "storage-driver": "btrfs", "userns-remap": "default"}'
    owner: root
    group: root
    mode: ug=r,o=

- name: install Docker
  apt:
    name: docker-ce
    state: latest

- name: install Docker-Compose
  pip:
    name:
      - docker-compose~={{ docker_compose_version }}

- name: install auto-completion for Docker-Compose
  get_url:
    url: https://raw.githubusercontent.com/docker/compose/{{ docker_compose_version }}/contrib/completion/bash/docker-compose
    dest: /etc/bash_completion.d/docker-compose
    owner: root
    group: root
    mode: a=r

- name: create base folder for image sources and service configurations
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: docker
    mode: ug=rwx,o=
  with_items:
    - "{{ docker_images_path }}"
    - "{{ docker_services_path }}"
